### https://zhuanlan.zhihu.com/p/399989820

In [1]:
import torch

In [2]:
a = torch.tensor([[1,2,3,4],[6,5,4,3]])

In [7]:
value,ind = a.topk(2,dim=0)
print(value)

tensor([[6, 5, 4, 4],
        [1, 2, 3, 3]])


In [11]:
x = torch.tensor([1,2,3])
x = x.expand((9,3))
print(x)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])


In [12]:
import copy

In [15]:
x = torch.tensor([1,2,3])
y = copy.copy(x)
z = y.expand((3,3))
print(z)
x[0]=2
print(z)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
tensor([[2, 2, 3],
        [2, 2, 3],
        [2, 2, 3]])


In [18]:
x = torch.tensor([1,2,3])
y = torch.tensor([1,2,4])

print(x.eq(y))
print(x.eq(1))

tensor([ True,  True, False])
tensor([ True, False, False])


In [22]:
#torch.sum(input,dim,keepdim=False,*dtype=None)->Tensor
x = torch.tensor([1,2,3]).expand((3,3))
print(x.sum(dim=1))

tensor([6, 6, 6])


In [27]:
#torch.rand(*size,*,out=None,dtype=None,layout=torch.strided,device=None,requires_grad=False)->Tensor
print(torch.rand(1,2,3,4))

tensor([[[[0.8837, 0.6503, 0.0206, 0.4809],
          [0.2218, 0.7487, 0.6825, 0.9631],
          [0.2564, 0.8850, 0.8549, 0.4764]],

         [[0.2703, 0.8195, 0.3932, 0.6462],
          [0.5664, 0.5032, 0.2350, 0.8012],
          [0.4549, 0.0221, 0.6972, 0.5634]]]])


In [28]:
#torch.randn(*size,out=None,dtype=None,layout=torch.strided,device=None,requires_grad=False)->Tensor
print(torch.randn(1,2,3,4))

tensor([[[[ 0.9412,  0.6065,  0.0264, -0.2627],
          [ 1.0490, -0.6218,  0.1176, -0.6667],
          [-1.0559,  0.3967,  0.2323,  0.7668]],

         [[-1.3839,  0.3994, -1.4914, -2.3200],
          [ 0.2814, -0.8055, -0.3459,  0.7364],
          [-0.0469,  0.4708,  1.1432, -0.8745]]]])


In [ ]:
#torch.randint(low=0,high,size,*,generator=None,out=None,dtype=None,layout=torch.strided,device=None,requires_grad=False)->Tensor
print(torch.randint(0,100,(20,20)))

In [59]:
#Tensor.random_(from_=0,to=None,*,generator=None)->Tensor
a = torch.Tensor(5)
print(a.random_(2,3))

tensor([2., 2., 2., 2., 2.])


In [61]:
#torch.randperm(n,*,generator=None,out=None,dtype=torch.int64,layout=torch.strided,device=None,requires_grad=False,pin_memory=False)->Tensor
#[0,n) random interger list 
print(torch.randperm(n=100))

tensor([84, 22, 61, 57, 95, 53, 63, 21, 73, 20, 74, 32, 51, 65, 34, 78, 96, 79,
        28, 15, 60, 56, 54, 50, 69, 35, 68,  6, 33, 94, 17, 97,  3, 86, 37, 36,
        19, 12, 26,  5, 23, 92, 70, 82, 77, 88, 98, 48, 10, 42, 27, 83, 39, 30,
        58, 91, 43, 64, 31, 11, 71, 40, 46, 90,  9, 16, 89, 55, 66,  1, 52, 49,
        80, 41, 87,  2,  7, 38, 67, 99, 44, 76, 75, 59,  4, 29, 85, 72,  8, 18,
        81, 25, 62, 24,  0, 14, 13, 93, 47, 45])


In [72]:
#Tensor.item()→ number
#tensor -> list
a = torch.tensor(1)
print(type(a))
print(a.item())
print(type(a.item()))

<class 'torch.Tensor'>
1
<class 'int'>
